GRANT CONNECT ON DATABASE timeline_data TO backup_user;
GRANT USAGE ON SCHEMA public TO backup_user;
GRANT USAGE ON SCHEMA timeline TO backup_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO backup_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO backup_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO backup_user;
GRANT SELECT ON ALL TABLES IN SCHEMA timeline TO backup_user;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA timeline GRANT SELECT ON TABLES TO backup_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON SEQUENCES TO backup_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA timeline TO backup_user;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA timeline GRANT SELECT ON SEQUENCES TO backup_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA timeline TO backup_user;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA timeline GRANT EXECUTE ON FUNCTIONS TO backup_user;